// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package todo

import (
	"github.com/99-66/go-gin-project-template/domains/todo/controllers"
	"github.com/99-66/go-gin-project-template/domains/todo/providers"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func RegisterTodo(DB *gorm.DB) (*controllers.TodoAPI, error) {
	todoRepository := providers.ProvideTodoRepository(DB)
	todoService := providers.ProvideTodoService(todoRepository)
	todoAPI := providers.ProvideTodoAPI(todoService)
	return todoAPI, nil
}
